spring.application.name=vitals-management
# Spring Boot server
server.port=9090

# Configuration Kafka (Step 1 -> Bus d'événements)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=medical-alerts

# Configuration InfluxDB (Stockage des données vitales)
influxdb.url=http://localhost:8086
influxdb.token=JNHeBeaoYHb1D_mcVAmfC9baC7nUzwQJjH1xISMlPPd4lsrJx4yDpyFh0w3tcBIf_3lOsSNtTKmfryg8kGmzfw==
influxdb.org=myorg
influxdb.bucket=medical_data

# Configuration MQTT (Réception capteurs)
# Port 1883 : standard MQTT après reconfiguration du container
mqtt.broker.url=tcp://127.0.0.1:1884
mqtt.client.id=vitals-management-client
mqtt.topic.prefix=sensors/vitals/


# Logging MQTT (réduit pour limiter le bruit)
logging.level.org.eclipse.paho.client.mqttv3=WARN
logging.level.org.springframework.integration.mqtt=WARN
logging.level.com.medtech.vitalsmanagement=INFO